name: build-auto-tagging
description: build-auto-tagging

inputs:
  pubspec-path:
    description: "Path to pubspec.yaml"
    default: "pubspec.yaml"
    required: false

outputs:
  version:
    description: "Version read from pubspec.yaml (x.y.z)"
    value: ${{ steps.read_version.outputs.version }}
  new_version:
    description: "Next patch version (x.y.(z+1))"
    value: ${{ steps.patch_version.outputs.new_version }}

runs:
  using: "composite"
  steps:
    - name: Read version from pubspec.yaml
      id: read_version
      shell: bash
      run: |
        FILE="${{ inputs.pubspec-path }}"

        if [ ! -f "$FILE" ]; then
          echo "::error::Pubspec.yaml not found at: $FILE"
          exit 1
        fi

        # Find 'version:' line
        VERSION_LINE=$(grep '^version:' "$FILE" || true)
        if [ -z "$VERSION_LINE" ]; then
          echo "::error::No 'version:' entry found in $FILE"
          exit 1
        fi

        # Strip 'version:' and build metadata (+...)
        VERSION=$(echo "$VERSION_LINE" \
          | sed 's/version:[[:space:]]*//; s/+.*//')

        if [ -z "$VERSION" ]; then
          echo "::error::Version string is empty after parsing"
          exit 1
        fi

        # Basic semver sanity check
        if ! echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "::error::Version '$VERSION' is not in propper x.y.z format"
          exit 1
        fi

        echo "::notice::pubspec version: $VERSION"
        echo "- [x] Read version from $FILE: $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Ensure no later major / major.minor tag exists
      id: check_tags
      shell: bash
      run: |
        VERSION='${{ steps.read_version.outputs.version }}'
        MAJOR=$(echo "$VERSION" | cut -d. -f1)
        MINOR=$(echo "$VERSION" | cut -d. -f2)
        PATCH=$(echo "$VERSION" | cut -d. -f3)

        echo "Checking tags against pubspec version: $MAJOR.$MINOR.$PATCH"

        git fetch --tags --force >/dev/null 2>&1 || true

        ALL_TAGS=$(git tag --list)
        if [ -z "$ALL_TAGS" ]; then
          echo "::notice::No tags in repo → skipping verification."
          exit 0
        fi

        SEMVER_TAGS=""
        for t in $ALL_TAGS; do
          base="$t"
          base="${base#v}"   # strip leading 'v' if present
          # only keep full semver tags
          if echo "$base" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            SEMVER_TAGS="$SEMVER_TAGS $base"
          fi
        done

        if [ -z "$SEMVER_TAGS" ]; then
          echo "::notice::No semver style tags (x.y.z or vx.y.z) found → skipping verification."
          exit 0
        fi

        HIGHEST_MAJOR=0
        HIGHEST_MAJOR_MINOR=""

        for v in $SEMVER_TAGS; do
          t_major=$(echo "$v" | cut -d. -f1)
          t_minor=$(echo "$v" | cut -d. -f2)

          # track highest major in repo
          if [ "$t_major" -gt "$HIGHEST_MAJOR" ]; then
            HIGHEST_MAJOR="$t_major"
          fi

          # track highest minor for same major as pubspec
          if [ "$t_major" -eq "$MAJOR" ]; then
            pair="$t_major.$t_minor"
            if [ -z "$HIGHEST_MAJOR_MINOR" ] || \
              [ "$(printf '%s\n' "$pair" "$HIGHEST_MAJOR_MINOR" | sort -V | tail -n1)" = "$pair" ]; then
              HIGHEST_MAJOR_MINOR="$pair"
            fi
          fi
        done

        echo "Highest major in tags: $HIGHEST_MAJOR"
        if [ -n "$HIGHEST_MAJOR_MINOR" ]; then
          echo "Highest major.minor for same major: $HIGHEST_MAJOR_MINOR"
        fi

        # Fail if there is a later major than in pubspec
        if [ "$HIGHEST_MAJOR" -gt "$MAJOR" ]; then
          echo "::error::Repo already has a later major release ($HIGHEST_MAJOR.x.x) than pubspec ($MAJOR.$MINOR.$PATCH)."
          exit 1
        fi

        # Fail if there is a later minor (for same major) than in pubspec
        if [ -n "$HIGHEST_MAJOR_MINOR" ]; then
          tag_minor=$(echo "$HIGHEST_MAJOR_MINOR" | cut -d. -f2)
          if [ "$tag_minor" -gt "$MINOR" ]; then
            echo "::error::Repo already has a later minor release ($HIGHEST_MAJOR_MINOR.x) than pubspec ($MAJOR.$MINOR.$PATCH)."
            exit 1
          fi
        fi

        echo "- [x] Tag verification passed successfully" >> $GITHUB_STEP_SUMMARY
        echo "::notice::Tag verification passed successfully."

    - name: Increase patch version
      id: patch_version
      shell: bash
      run: |
        VERSION='${{ steps.read_version.outputs.version }}'
        IFS=. read MAJOR MINOR PATCH <<< "$VERSION"

        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

        echo "::notice::new patch version: $NEW_VERSION"
        echo "- [x] New Tag version: $NEW_VERSION" >> $GITHUB_STEP_SUMMARY        
        echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"