name: flutter-test
description: flutter-test

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml
        cache: true

    - name: Cache pub packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          **/.dart_tool
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Flutter pub get
      run: flutter pub get

    - name: Generate localizations and verify they are commited
      run: |
        if [ -f "l10n.yaml" ]; then
          flutter gen-l10n
        
          if ! git diff --quiet; then
            echo "::error::Localization files are not committed or outdated!"
            echo "Run 'flutter gen-l10n' locally and commit the generated files."
            git diff
            exit 1
          else 
            echo "✔ Localization files are up to date."
          fi
        else
          echo "::notice::No l10n.yaml found → skipping localization verification"
        fi        

    - name: Enforce formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze
      run: dart analyze .

    - name: Run tests
      run: flutter test